name: Tests API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      API_BASE_URL: 'http://localhost:3000'

    steps:
    
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Instalando as dependências
      run: npm install 

    - name: Instalar dependências do relatório mochawesome
      run: npm install -g mochawesome-merge mochawesome-report-generator

    - name: Iniciando o servidor
      run: npm run dev &
    
    - name: Executando os testes
      run: npm run test
      
    - name: Mesclando relatórios JSON e Gerando HTML
      run: |
        npm run report:merge
        npm run report:html

    - name: Upload do artefato do relatório mochawesome
      uses: actions/upload-artifact@v4
      with:
        name: Relatorio-Mochawesome
        path: mochawesome-report/mochawesome.html
